version: '3'

services:
  activity-detection:
    build: .
    volumes: 
      - .:/usr/src/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports: 
      - 5001:80
    devices:
      - /dev/video0:/dev/video0
    environment:
      - "DISPLAY=$DISPLAY"